baseURL = 'https://pantuflas.github.io/hugo-blog/'
languageCode = 'en-us'
theme = "hugo-theme-nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "about"
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "/posts"

[params]
author = "Hugo Nightfall"
user = "Pantufla"
hostname = "githubpages"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/gohugoio"

[[params.social]]
key = 1
name = "twitter"
url = "https://www.example.com"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.example.com"

[[params.social]]
key = 3
name = "email"
url = "mailto:email@example.com"